### ISSUE TITLE
doubt on how to save and load model

### ISSUE THREAD

**Issue by harsha-sharechat-account** [etlundquist/rankfm#24]
1.can you pls explain how to save and loas the best model.
2.also is there any way that you could parallelise(use multiprocessing) if possible in the training /prediction part as i have observed that only one core of my machine is being used,

**Comment by etlundquist** [comment]
1. right now there's no inherent model save/load functionality. You could likely serialize/deserialize using pickle (as this should work with all Python objects) but I haven't tried it yet. 
2. I've tried to parallelize using the OpenMP/prange()functionality for thread-based parallelism included in Cython (you can actually see this in one of the pushed feature branches) but it actually ran slower than single threaded when I was testing. I'm not sure why this was happening but until I have time to really investigate it's indeed single-threaded. Sorry about that!

**Comment by augustodn** [comment]
Despite this issue being closed, I confirm pickle works as expected letting you save and reload the model from a binary file.
