### ISSUE TITLE
Adding time of interaction feature

### ISSUE THREAD

**Issue by guyba-tr** [etlundquist/rankfm#28]
Hi,
In Rendle's original paper on FM (https://www.csie.ntu.edu.tw/~b97053/paper/Rendle2010FM.pdf), he used a feature that captures the time of the user-item interaction. This should improve the model.

In your model, from what I see, we can input user features, item features and the interactions themselves.
How can I add the time of the interaction into the mix?

**Comment by etlundquist** [comment]
Hi @guyba-tr yeah agreed that these "context" features that are not fixed to any particular user or item but rather each interaction context (e.g. DoW, ToD, browser, items-in-cart, etc.) would be theoretically valuable. Unfortunately, adding them into this implementation would significantly change the internal data model / training routine. This was a shortcut I took in the initial development to keep things fast/simple, and I may come back to this at some point and overhaul things to allow these "contextual" features, but for now they are not supported. If you can find another implementation that supports this kind of thing please let me know so I can look at how they do it efficiently! Sorry mate :(
