### ISSUE TITLE
NaNs leading to KeyError while comparing arrays during user_item_index vectors generation

### ISSUE THREAD

**Issue by suhassatish** [etlundquist/rankfm#30]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-87-233066c6f842> in <module>
----> 1 model.fit(interactions, user_features, item_features, sample_weight, epochs=50, verbose=True)

~/.virtualenv/turicreate/lib/python3.8/site-packages/rankfm/rankfm.py in fit(self, interactions, user_features, item_features, sample_weight, epochs, verbose)
    263 
    264         self._reset_state()
--> 265         self.fit_partial(interactions, user_features, item_features, sample_weight, epochs, verbose)
    266 
    267 

~/.virtualenv/turicreate/lib/python3.8/site-packages/rankfm/rankfm.py in fit_partial(self, interactions, user_features, item_features, sample_weight, epochs, verbose)
    287             self._init_features(user_features, item_features)
    288         else:
--> 289             self._init_all(interactions, user_features, item_features, sample_weight)
    290 
    291         # determine the number of negative samples to draw depending on the loss function

~/.virtualenv/turicreate/lib/python3.8/site-packages/rankfm/rankfm.py in _init_all(self, interactions, user_features, item_features, sample_weight)
    133 
    134         # map the user/item features to internal index positions
--> 135         self._init_features(user_features, item_features)
    136 
    137         # initialize the model weights after the user/item/feature dimensions have been established

~/.virtualenv/turicreate/lib/python3.8/site-packages/rankfm/rankfm.py in _init_features(self, user_features, item_features)
    200                 self.x_uf = np.ascontiguousarray(x_uf.sort_index(), dtype=np.float32)
    201             else:
--> 202                 raise KeyError('the users in [user_features] do not match the users in [interactions]')
    203         else:
    204             self.x_uf = np.zeros([len(self.user_idx), 1], dtype=np.float32)

KeyError: 'the users in [user_features] do not match the users in [interactions]'

**Comment by etlundquist** [comment]
I'm not sure I 100% understand the issue, but if you have NaNs in your training data (either user/item IDs or features) that should raise an exception - the package does not support missing data. If that's the case then I'm going to close the issue, but if it's something else please provide a bit more detail/context.
